package oodj_project.core.security;

public enum Permission {
    CREATE_USERS,
    READ_USERS,
    UPDATE_USERS,
    DELETE_USERS,

    CREATE_MODULES,
    READ_MODULES,
    UPDATE_MODULES,
    DELETE_MODULES,

    CREATE_CLASSES,
    READ_CLASSES,
    UPDATE_CLASSES,
    DELETE_CLASSES,

    TEACH_CLASSES,
    ASSIGN_TEACHER,

    READ_ENROLLMENT_REPORT,

    READ_LECTURER_WORKLOAD
}
