package oodj_project.core.security;

public enum Permission {
    CREATE_USERS,
    READ_USERS,
    UPDATE_USERS,
    DELETE_USERS,

    CREATE_GRADES,
    READ_GRADES,
    UPDATE_GRADES,
    DELETE_GRADES,

    CREATE_MODULES,
    READ_MODULES,
    UPDATE_MODULES,
    DELETE_MODULES,

    CREATE_CLASSES,
    READ_CLASSES,
    READ_ALL_CLASSES,
    UPDATE_CLASSES,
    DELETE_CLASSES,

    CREATE_ASSESSMENTS,
    READ_ASSESSMENTS,
    READ_ALL_ASSESSMENTS,
    UPDATE_ASSESSMENTS,
    DELETE_ASSESSMENTS,

    GRADE_ASSESSMENTS,
    READ_ASSESSMENT_RESULTS,
    READ_ALL_ASSESSMENT_RESULTS,

    TEACH_CLASSES,
    ASSIGN_TEACHER,
    
    READ_TEAM_MANAGEMENT,
    ASSIGN_SUPERVISOR,

    READ_ENROLLMENT_REPORT,

    READ_LECTURER_WORKLOAD,

    ENROLL_CLASSES,
    UNENROLL_CLASSES,
    GIVE_FEEDBACKS,

    CREATE_FEEDBACKS,
    READ_FEEDBACKS,
    UPDATE_FEEDBACKS,
    DELETE_FFEDBACKS
}
